services:
  unpin:
    image: yoursfunny/unpinbot:latest
    restart: always
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      # UNPINBOT_LANG: zh
      # UNPINBOT_STATE_PATH: pers_data/state.json
      # RUST_LOG: info
      LOCAL_USER_ID: '1000'
    volumes:
      - ./pers_data:/app/pers_data
    container_name: unpin
